theme: architect # jekyll-theme-minimal
title: The Modern Aoidos Blog
description: The Modern Aoidos is a digital melting pot where the ancient tradition of storytelling rubs shoulders with current narratives. An Aoidos was a fabled bard whose music and poetry told stories that preserved myths long after their subjects have disappeared from human memory. While the mythology has dissipated today, its spirit lives on in tales of business innovation, technological progress and life itself.
domain: the-modern-aoidos.github.io       
url: https://the-modern-aoidos.github.io  