# theme: # timemachine # tactile # slate # modernist # minima # midnight # merlot # leapday # hacker # dinky # cayman # architect # jekyll-theme-minimal
remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: The Modern Aoidos Blog
description: An Aoidos was a fabled bard whose music and poetry told stories that preserved myths long after their subjects have disappeared from human memory.
domain: the-modern-aoidos.github.io       
url: https://the-modern-aoidos.github.io  
# google_analytics: [Your Google Analytics tracking ID]